// export const images = [
//     {
//       id: '01',
//       src: 'https://images.unsplash.com/photo-1602024242516-fbc9d4fda4b6?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1500&q=80',
//       alt: 'Awesome watch',
//     },
//     {
//       id: '02',
//       src: 'https://images.unsplash.com/photo-1451290337906-ac938fc89bce?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1777&q=80',
//       alt: 'Awesome watch',
//     },
//     {
//       id: '03',
//       src: 'https://images.unsplash.com/photo-1568010434570-74e9ba7126bc?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1500&q=80',
//       alt: 'Awesome watch',
//     },
//     {
//       id: '04',
//       src: 'https://images.unsplash.com/photo-1569411032431-07598b0012c2?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80',
//       alt: 'Awesome watch',
//     },
//     {
//       id: '05',
//       src: 'https://images.unsplash.com/photo-1565440962783-f87efdea99fd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=936&q=80',
//       alt: 'Awesome watch',
//     },
//     {
//       id: '06',
//       src: 'https://images.unsplash.com/photo-1548169874-53e85f753f1e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1420&q=80',
//       alt: 'Awesome watch',
//     },
    
//   ]
  export const products =  [
    {
      "img": "https://www.geekbuying.com/item/ILIFE-A80-Plus-Robot-Vacuum-Mop-Cleaner-504826.html",
      "imageUrl": "https://img.gkbcdn.com/p/2022-06-15/ILIFE-A80-Plus-Robot-Vacuum-Mop-Cleaner-504826-0._w280_p1_.jpg",
      "label_img": "https://img.gkbcdn.com/s3/l/label/Label28.png?20221215",
      "name": "ILIFE A80 Plus",
      "description": "ILIFE A80 Plus Robot Vacuum Cleaner 2 In 1 Vacuuming and Mopping 1000Pa Suction Gyroscopic Navigation Carpet Pressurization 2400mAh Battery 100Mins Run Time 450ml Dust Tank APP Control - Pink",
      "price": 89.99,
      "category": "electroncs",
      "list-price": "$269.99",
      "review": "https://www.geekbuying.com/customer-reviews/ILIFE-A80-Plus-Robot-Vacuum-Mop-Cleaner-504826/",
      "review_num": 29,
      "favite_count": 90,
      "id": 1
    },
    {
      "img": "https://www.geekbuying.com/item/Shunzao-Z11-MAX-Hand-held-Cordlesss-Vacuum-Cleaner-497646.html",
      "imageUrl": "https://img.gkbcdn.com/p/2022-03-10/Shunzao-Z11-MAX-Hand-held-Cordlesss-Vacuum-Cleaner-497646-0._w280_p1_.jpg",
      "label_img": "https://img.gkbcdn.com/s3/l/label/Label28.png?20221215",
      "name":"Shunzao Z11 Max Cordless",
      "description": "Shunzao Z11 Max Cordless Vacuum Cleaner 26000Pa 150AW Suction Power 125000RPM 2500mAh Battery 60Mins Runtime Five-Layer Filtration System Anti-Winding Floor Brush Real-Time Display - Orange",
      "price": 175.99,
     "category": "electroncs",
      "list-price": 339.99,
      "review": "https://www.geekbuying.com/customer-reviews/Shunzao-Z11-MAX-Hand-held-Cordlesss-Vacuum-Cleaner-497646/",
      "review_num": 13,
      "favite_count": 77,
      "id":2
    },
    {
      "img": "https://www.geekbuying.com/item/ILIFE-M50-Handheld-Car-Vacuum-Cleaner-Black-518295.html",
      "imageUrl": "https://img.gkbcdn.com/p/2022-11-18/ILIFE-M50-Handheld-Car-Vacuum-Cleaner-Black-518295-0._w280_p1_.jpg",
      "label_img": "https://img.gkbcdn.com/s3/l/label/Label28.png?20221215",
      "name": "ILIFE M50 Handeld",
      "description": "ILIFE M50 Handheld Car Vacuum Cleaner, 15000Pa Suction, 150ml Dust Cup, 2500mAh Battery, 32min Runtime, LED Lights",
      "price": 39.99,
      "category": "electroncs",
      "list-price": "$69.99",
      "review": "https://www.geekbuying.com/customer-reviews/ILIFE-M50-Handheld-Car-Vacuum-Cleaner-Black-518295/",
      "review_num": 18,
      "favite_count": 44,
      "id":3
    },
    {
      "img": "https://www.geekbuying.com/item/Roborock-S7-Pro-Ultra-Robot-Vacuum-Cleaner-White-507633.html",
      "imageUrl": "https://img.gkbcdn.com/p/2022-06-25/Roborock-S7-Pro-Ultra-Robot-Vacuum-Cleaner-White-506889-2._w280_p1_.jpg",
      "label_img": "https://img.gkbcdn.com/s3/l/label/Label8.png?20221215",
      "name": "Roborock S7 Pro",
      "description": "Roborock S7 Pro Ultra Robot Vacuum Cleaner Self-Cleaning & Emptying 5100Pa Powerful Suction 5200mAh Battery 30% Faster Charging LDS Navigation 400ml Dustbin Sonic Mopping Auto-Lifting Mop Alexa Google Home App Control - White",
      "price": 987.90,
      "category": "electroncs",
      "list-price": "$1491.25",
      "review": "https://www.geekbuying.com/customer-reviews/Roborock-S7-Pro-Ultra-Robot-Vacuum-Cleaner-White-507633/",
      "review_num": 29,
      "favite_count": 165,
      "id":4
    },
    {
      "img": "https://www.geekbuying.com/item/Proscenic-A9-Smart-Air-Purifier-LED-Digital-Display-White-459704.html",
      "imageUrl": "https://img.gkbcdn.com/p/2021-05-13/Proscenic-A9-Smart-Air-Purifier-White-459704-0._w280_p1_.jpg",
      "label_img": "https://img.gkbcdn.com/s3/l/label/Label28.png?20221215",
      "name": "Proscenic A9 Smart Purifier",
      "description": "Proscenic A9 Smart Air Purifier LED Digital Display Adjustable Wind Speed APP Control, Remove 99.97% Dust, Pet Dander, Smoke, Pollen, Odor - White",
      "price": 109.99,
      "category": "electroncs",
      "list-price": "$197.99",
      "review": "https://www.geekbuying.com/customer-reviews/Proscenic-A9-Smart-Air-Purifier-LED-Digital-Display-White-459704/",
      "review_num": 15,
      "favite_count": 80,
      "id":5
    },
    {
      "img": "https://www.geekbuying.com/item/2PCS-Xiaomi-Aqara-Temperature-Humidity-Sensor-White-425369.html",
      "imageUrl": "https://img.gkbcdn.com/p/2018-10-25/xiaomi-aqara-temperature-humidity-sensor-white-1574132919397._w280_p1_.jpg",
      "label_img": "",
      "name":"Temperature Humidity Sensor",
      "description": "2PCS Xiaomi Aqara Temperature Humidity Sensor Works with Apple Homekit, Other Aqara Smart Home Devices - White",
      "price": 29.99,
      "category": "electroncs",
      "list-price": "$36.99",
      "review": "https://www.geekbuying.com/customer-reviews/2PCS-Xiaomi-Aqara-Temperature-Humidity-Sensor-White-425369/",
      "review_num": 1,
      "favite_count": 26,
      "id":6
    },
    {
      "img": "https://www.geekbuying.com/item/ILIFE-V8-Plus-Robot-Vacuum-Cleaner-EU-Plug-503291.html",
      "imageUrl": "https://img.gkbcdn.com/p/2022-06-14/ILIFE-V8-Plus-Robot-Vacuum-Cleaner-EU-Plug-503291-0._w280_p1_.jpg",
      "label_img": "https://img.gkbcdn.com/s3/l/label/Label28.png?20221215",
      "name":"Vacuum Cleaner",
      "description": "ILIFE V8 Plus Robot Vacuum Cleaner 1000Pa Suction 2-in-1 Vacuuming and Mopping Gyroscope Navigation 2400mAh Battery 80Mins Run Time 750ml Large Dustbin 300ml Water Tank Auto Obstacle Avoidance - White",
      "price": 94.99,
      "category": "electroncs",
      "list-price": "$249.99",
      "review": "https://www.geekbuying.com/customer-reviews/ILIFE-V8-Plus-Robot-Vacuum-Cleaner-EU-Plug-503291/",
      "review_num": 12,
      "favite_count": 40,
      "id":7
    },
    {
      "img": "https://www.geekbuying.com/item/Roborock-S7-Robot-Vacuum-Cleaner-2500Pa-Powerful-Suction-475168.html",
      "imageUrl": "https://img.gkbcdn.com/p/2021-02-20/roborock-s7-robot-vacuum-cleaner-2500pa-powerful-suction-1613791182553._w280_p1_.jpg",
      "label_img": "",
      "name": "Sonic Mopping Auto Mop ",
      "description": "Roborock S7 Robot Vacuum Cleaner with Sonic Mopping Auto Mop Lifting 2500Pa Powerful Suction LiDAR Navigation Ultrasonic Carpet Recognition 5200mAh Battery 470ml Dustbin 300ml Water Tank Alexa APP Control for Pets Hair, Carpets and Hard Floor - Black",
      "price": 459.99,
      "category": "electroncs",
      "list-price": "$699.99",
      "review": "https://www.geekbuying.com/customer-reviews/Roborock-S7-Robot-Vacuum-Cleaner-2500Pa-Powerful-Suction-475168/",
      "review_num": 19,
      "favite_count": 61,
      "id":8
    },
    {
      "img": "https://www.geekbuying.com/item/ROIDMI-EVA-3-in-1-3200Pa-Robot-Vacuum-500461.html",
      "imageUrl": "https://img.gkbcdn.com/p/2022-05-13/ROIDMI-EVA-3-in-1-3200Pa-Robot-Vacuum-500461-0._w280_p1_.jpg",
      "label_img": "https://img.gkbcdn.com/s3/l/label/Label54.png?20221215",
      "name": "ROIDMI Vacuum Cleaner",
      "description": "ROIDMI EVA Smart Robot Vacuum Cleaner Self-Cleaning & Emptying 3200Pa Powerful Suction 3-in-1 Vacuuming Sweeping Mopping LDS Navigation Auto-Drying 3 Modes 5200mAh Battery LED Display Alexa & Google Home APP Control - White",
      "price": 649.99,
      "category": "electroncs",
      "list-price": "$899.99",
      "review": "https://www.geekbuying.com/customer-reviews/ROIDMI-EVA-3-in-1-3200Pa-Robot-Vacuum-500461/",
      "review_num": 34,
      "favite_count": 95,
      "id":9
    },
    {
      "img": "https://www.geekbuying.com/item/Liectroux-ZK901-6500Pa-Lidar-Robot-Vacuum-Cleaner-497699.html",
      "imageUrl": "https://img.gkbcdn.com/p/2022-03-10/LIECTROUX-ZK901-6500Pa-Lidar-Robot-Vacuum-Cleaner-497699-0._w280_p1_.jpg",
      "label_img": "https://img.gkbcdn.com/s3/l/label/Label28.png?20221215",
      "name": "Liectroux Vacuum Cleaner",
      "description": "Liectroux ZK901 Robot Vacuum Cleaner 3 In 1 Vacuuming Sweeping and Mopping Laser Navigation 6500Pa Suction 5000mAh Battery Voice Control Breakpoint Resume Clean & Mapping APP Control - Black",
      "price": 209.99,
      "category": "electroncs",
      "list-price": "$399.99",
      "review": "https://www.geekbuying.com/customer-reviews/Liectroux-ZK901-6500Pa-Lidar-Robot-Vacuum-Cleaner-497699/",
      "review_num": 6,
      "favite_count": 57,
      "id":10
    },
    {
      "img": "https://www.geekbuying.com/item/UWANT-B100-E-Multifunctional-Spot-Cleaner-Washing-Suction-Integration-493110.html",
      "imageUrl": "https://img.gkbcdn.com/p/2022-01-08/UWANT-B100-E-Multifunctional-Spot-Cleaner-Washing-Suction-Integration-493110-0._w280_p1_.jpg",
      "label_img": "https://img.gkbcdn.com/s3/l/label/Label8.png?20221215",
      "name": " Cloth Cleaning Machine",
      "description": "UWANT B100-E Multifunctional Cloth Cleaning Machine Vacuum Spot Cleaner Integration Washing Machine 12000Pa Suction 1800ML Water Tank Self-cleaning Low Noise for Carpet Sofa Curtain Mattress Upholstery - White",
      "price": 209.99,
      "category": "electroncs",
      "list-price": "$299.99",
      "review": "https://www.geekbuying.com/customer-reviews/UWANT-B100-E-Multifunctional-Spot-Cleaner-Washing-Suction-Integration-493110/",
      "review_num": 16,
      "favite_count": 80,
      "id": 11
    },
    {
      "img": "https://www.geekbuying.com/item/Jimmy-BX7-Pro-Handheld-Anti-mite-Vacuum-Cleaner-498211.html",
      "imageUrl": "https://img.gkbcdn.com/p/2022-03-24/Jimmy-BX7-Pro-Handheld-Anti-mite-Vacuum-Cleaner-498211-0._w280_p1_.jpg",
      "label_img": "https://img.gkbcdn.com/s3/l/label/Label54.png?20221215",
      "name":" Anti-Mite Vacuum Cleaner ",
      "description": "JIMMY BX7 Pro Anti-Mite Vacuum Cleaner 700W Powerful Motor UV-C Sterilization Killing 99.99% Bacteria 60 Celsius Constant High-Temperature Intelligent Dust Recognition 3 Modes LED Display for Bed, Pet Hair, Sofa, Clothing - Blue",
      "price": 139.99,
      "category": "electroncs",
      "list-price": "$199.99",
      "review": "https://www.geekbuying.com/customer-reviews/Jimmy-BX7-Pro-Handheld-Anti-mite-Vacuum-Cleaner-498211/",
      "review_num": 38,
      "favite_count": 73,
      "id": 12
    },
    {
      "img": "https://www.geekbuying.com/item/Ultenic-K20-Dual-Basket-Air-Fryer-518081.html",
      "imageUrl": "https://content1.geekbuying.com/V1.4/en/images/geek_loading.png",
      "label_img": "https://img.gkbcdn.com/s3/l/label/Label28.png?20221215",
      "name": "Hot Air Fryer ",
      "description": "Ultenic K20 Dual Basket Hot Air Fryer 2850W 8L Capacity Dual Independent Cooking Zone Touch Screen100 Online Recipes 6 Programmes Digital Display with 6 Presets Dishwasher-Safe - Black",
      "price": 139.99,
      "category": "electroncs",
      "list-price": "$169.99",
      "review": "https://www.geekbuying.com/customer-reviews/Ultenic-K20-Dual-Basket-Air-Fryer-518081/",
      "review_num": 6,
      "favite_count": 37,
      "id": 13
    },
    {
      "img": "https://www.geekbuying.com/item/JIMMY-H9-Pro-Flexible-Smart-Handheld-Cordless-Vacuum-Cleaner-Gold-471025.html",
      "imageUrl": "https://content1.geekbuying.com/V1.4/en/images/geek_loading.png",
      "label_img": "",
      "name":"Vacuuming Mopping 200AW",
      "description": "JIMMY H9 Pro Mopping Version Handheld Cordless Vacuum Cleaner 2 in 1 Vacuuming Mopping 200AW 25000Pa Powerful Suction, 80 Minutes Run Time, 200ml Water Tank, Auto Power Adjust LED Display Removable Battery With Rechargeable Stand Holder - Gold",
      "price": 379.99,
      "category": "electroncs",
      "list-price": "$599.99",
      "review": "https://www.geekbuying.com/customer-reviews/JIMMY-H9-Pro-Flexible-Smart-Handheld-Cordless-Vacuum-Cleaner-Gold-471025/",
      "review_num": 5,
      "favite_count": 32,
      "id": 14
    },
    {
      "img": "https://www.geekbuying.com/item/Calmdo-CD-AF25EU-1800W-25L-Extra-Large-Air-Fryer-Toaster-Oven-508997.html",
      "imageUrl": "https://content1.geekbuying.com/V1.4/en/images/geek_loading.png",
      "label_img": "https://img.gkbcdn.com/s3/l/label/Label28.png?20221215",
      "name": " Smart Air Fryer Toaster Oven",
      "description": "Calmdo CD-AF25EU 12 in 1 Smart Air Fryer Toaster Oven 25L Extra-Large 1800W 12 Preset Functions with 4-layer Grill LED Digital Touch Screen - Black",
      "price": 139.95,
      "category": "electroncs",
      "list-price": "$199.99",
      "review": "https://www.geekbuying.com/customer-reviews/Calmdo-CD-AF25EU-1800W-25L-Extra-Large-Air-Fryer-Toaster-Oven-508997/",
      "review_num": 6,
      "favite_count": 49,
      "id": 15
    }
  ]